server:
  port: 8888
  servlet:
    context-path: "/api/v1"


spring:
  data:
    jpa:
      repositories:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop
    username: eshop
    password: esh0p

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

jwt:
  secret: "secr3t"
  expirationMs: 180 000 000
  cookieName: "apiCook"
logging:
  level:
    org:
      springframework:
        security: DEBUG